apiVersion: v1
kind: Secret

metadata:
  name: upload-server-secret
  namespace: upload-server

type: Opaque

# A informação aqui já deve estar em base64
data:
  DATABASE_URL: 'cG9zdGdyZXNxbDovL2RvY2tlcjpkb2NrZXJAbG9jYWxob3N0OjU0MzIvdXBsb2Fk' # postgresql://docker:docker@localhost:5432/upload
  CLOUDFLARE_ACCOUNT_ID: 'Iw==' # '#'
  CLOUDFLARE_ACCESS_ID: 'Iw==' # '#'
  CLOUDFLARE_SECRET_ACCESS_KEY: 'Iw==' # '#'
